apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20231028003658.0.0+build.02e9424
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20231028003658.0.0+build.02e9424
  releaseNotes: |
    Release v20231028003658.0.0+build.02e9424 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-27-10-2023-18-30-01-919930361/where-for-dinner-search-my-apps-bundle@sha256:0adac7dfa667a44a5a7e2533d5b267c6a5b1f576eee6ea1ab63c6c4b7d7dfa2b
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

