apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20231028003623.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20231028003623.0.0+build.02e9424
  releaseNotes: |
    Release v20231028003623.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-27-10-2023-18-30-01-919930361/where-for-dinner-my-apps-bundle@sha256:23c64917af87805439652b9ccee39c0f68a32619eb7541c25d3a09fca6ca4365
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

