apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-notify.my-apps.tap.20231028003636.0.0+build.02e9424
spec:
  refName: where-for-dinner-notify.my-apps.tap
  version: 20231028003636.0.0+build.02e9424
  releaseNotes: |
    Release v20231028003636.0.0+build.02e9424 of package where-for-dinner-notify.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-27-10-2023-18-30-01-919930361/where-for-dinner-notify-my-apps-bundle@sha256:34acea31e00afee74ceb4a20f08fcd0209cd11c964fa08b615f769b92c0e7dae
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

